// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thyytjpyvprdpmomgrcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeXl0anB5dnByZHBtb21ncmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNjc3NTMsImV4cCI6MjA1MTg0Mzc1M30.9hBU7nGpFe1BsBdctx0Ab5gtBdYY3UgLk2UYCBEMOsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);